### ISSUE TITLE
Ko 2 distance- How would I cacluclate that? - Schlaufman

### ISSUE THREAD

**Issue by Alex162** [Alex162/Mg-K-Hollyweirdos#10]
Not sure calculating the distance would add much / anything to the paper really. However, it costs practically nothing to include it in terms of space, provided we can actually calcualte the distance to the star... Which I can't think how we'd do give the information we have. Thoughts?

**Comment by andycasey** [comment]
Sure -- calculate it.

First thing you need to do is find the distance to Ko 2. Then calculate, given an on-sky difference of 2.54 degrees (is that what it was), how far that would be  at the distance of Ko 2.

Google: astropy angular coordinates to distance

The other thing to do would be to look at the magnitude of your star and the stars in Ko 2. Your star should at least be at the same approximate visual magnitude as Ko 2 stars if they are related.

**Comment by Alex162** [comment]
Distance calculated and text updated. for easy reference, distance (absolute minimum) was 1.74 kpc from the cluster, while the cluster is estimated at 3 pc in size
