### ISSUE TITLE
[Alpha/Fe] labels - Ho

### ISSUE THREAD

**Issue by Alex162** [Alex162/Mg-K-Hollyweirdos#11]
Anna brought up that there's a seccond paper where, among other things, the cannon is re-applied that ultimately results in improvements in accuracy to the [alpha/Fe] label. This label is pretty important to us. Below is the relevant passage from https://arxiv.org/abs/1609.03195 about what they did differently, and why they did it.

On the one hand, using the better values for [alpha/Fe]  in the table and in figures might make sense. BUT, we used the values for [alpha/Fe], and the model associated with it, for our abundance estimates, residual gaussian fitting etc, and pretty much basically everything we've done. In otherwords, for consistency, should we report the [alpha/Fe] that we actually used rather than the better one? Must we repeat the whole project with the better [alpha/Fe] values? Should we report values from both papers in the table, with a footer explaining the significance of each?

I'm inclined towards the last option, but I'm undecided.

Passage:
In Paper 1, we fit an independent spectral model at every spectral pixel. However, there are features in LAMOST spectra that arise from effects in a different velocity system from that of the star: for example, diffuse interstellar bands (DIBs) and the Na
I doublet are interstellar absorption features originating from intervening material. We noticed by examining the leading coefficients of an initial Cannon model (see Figure 3) that The Cannon was “learning” to use these features to predict labels intrinsic to the star, particularly [α/M], and that this introduced radial velocity- dependent systematic errors into the label estimates1. The leading coefficients of an initial Cannon model also indicated that the imperfectly corrected telluric bands, originating in the Earth’s atmosphere, left small, but significant, velocity-dependent effects in the rest-frame spectra of the stars.
To prevent The Cannon from using these features spuriously, we masked them out by setting the inverse variances corresponding to these pixels to be zero. To be conservative, roughly half of each spectrum was masked, but because the most important features for our labels of interest were preserved, this still improved our label estimates.

**Comment by andycasey** [comment]
This is a good point.

I think things could get quickly muddled if we are using multiple [alpha/M]  that come from different models, since we rely on the model's  prediction  to find Mg-poor looking stars.

First thing to  do is cross-match all your candidates against Anna's updated catalog and look at the differences. Can you make that plot?

**Comment by Alex162** [comment]
I assume your talking about diferences in [alpha/Fe]. I can make that plot, assuming I can find Anna's updated catalogue and its a fits file. I'll try and find it and let you know if i fail

**Comment by Alex162** [comment]
Done. The changes the grouping of our data is extremely tiny, and so (at present) no action of any kind has been taken.
