### ISSUE TITLE
Plot similar to the current comparison with NGC 2419 and NGC 2808, but against the galaxy (Apogee and Koboyashi data?) - Latanzio

### ISSUE THREAD

**Issue by Alex162** [Alex162/Mg-K-Hollyweirdos#14]
If we have room (both in terms of space and figure count within MNRAS rules) it might be nice to show the figure explicitly, or else add galactic data to Figure 3, although a lot of the information is already inferrable from Figure 4.

**Comment by andycasey** [comment]
you could add it as small scatter points in the same way  the apogee ones are: they would just sit in the background of the figure:

`ax.scatter(galaxy["mg_fe"], galaxy["k_fe"], s=1, zorder=-1, c="#666666", alpha=0.5)`

**Comment by Alex162** [comment]
Done. Apogee data is added, discussion refers to the Apogee data now, rather than kobayashi. the actual numbers didn't change anyway.

**Comment by andycasey** [comment]
Close issues when they are done and feel the satisfaction!
