### ISSUE TITLE
Text between section and subsectino labels- Tout

### ISSUE THREAD

**Issue by Alex162** [Alex162/Mg-K-Hollyweirdos#5]
Is it necessary to have a brief general comment bewteen section headings and subsection headings (eg. 2. Method and Observations // 2.1: Candidate selection form LAMOST spectra

**Comment by andycasey** [comment]
Not necessary, but if Tout wants  something  there, just add some signpost filler text or reorganise a little.

**Comment by Alex162** [comment]
Since I posted this, we've extended onto 7 pages (mostly because its put in some dumb spaces to make paragraphs line up at top/bottom of pages). So atm I'm disinclined to add filler text, but I'll see how things shape out if anything else changes

**Comment by andycasey** [comment]
You can add one sentence of filler  text: there will be text cuts made.

I repeat myself: don’t concern yourself about the page limit. It is the last (and easiest) thing to consider.
