### ISSUE TITLE
Possibly reduce number of references in [K/Fe] abundance ratio estimation para - Tout

### ISSUE THREAD

**Issue by Alex162** [Alex162/Mg-K-Hollyweirdos#6]
Tout comments that there are too many references here, and questions which were actually used

**Comment by andycasey** [comment]
I am sure you can figure this one out without input from me

**Comment by Alex162** [comment]
No action taken; I don't know enough to decide who's work was important and whose wasn't, so I'm just assuming that everyone was relevant here.
