### ISSUE TITLE
Fancy dibs plot - Ness

### ISSUE THREAD

**Issue by Alex162** [Alex162/Mg-K-Hollyweirdos#9]
Possibly worth looking at. Not as yet attempted, but anticipate issues trying to use the wavelength-dependent residuals.

**Comment by andycasey** [comment]
It is worth looking at! And easy enough to plot.

Maybe we will leave this for referee stage if they ask about interstellar absorption w.r.t. Na

**Comment by Alex162** [comment]
Done figure; no feature at Na wavelength (5900 ish) is observed, though whether this means that there necesarily is no contribution is unlikley; the histogram using dust absorption data did show that the Na enhanced stars were associated with E(B-V) values generally higher than those that weren't Na enhanced. At present no action taken, although arguably a rephrase or a mention of our examining this plot could be in order.
